# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 718ca08d0d94ce01a34329bdc0fc2b59cd5b0ad9f2700875a5c5c804391d2db95f114c7eacf4061ca5907a849d40fb73dc674478776926fdcc7a5f8d0341b13b

test:
  secret_key_base: 70f622f05370dad431cfc561f6cbecb76d022fdca0d590c385ac45caffa7b54cd6a24110dd2cc25f5b8ca0c73e0a74a2c184eafdca08e5313101b24d1c2e5fc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
